"""A plan as an eval fixture script (evals/player.py), one line per claim and per operation."""

from __future__ import annotations

from typing import Any

import yaml

from wmk_adapter.plan import Plan

HEADER = """\
# Generated by `{command}` from the sources in this folder: do not edit by hand.
# {{{{at:<source>:<offset>}}}} is the chunk holding that character of the source, {{{{ref:<slug>}}}}
# a node created by an earlier write, {{{{agent:self}}}} the agent writing through the gateway.
"""


def script_text(plan: Plan, command: str) -> str:
    """The fixture script; `command` names what generated it."""
    out = [HEADER.format(command=command)]
    for step in plan.script():
        if "ingest" in step:
            out.append(f"- ingest: {flow(step['ingest'])}\n")
            continue
        write = step["write"]
        out.append(f"- write:\n    claim: {flow(write['claim'])}\n")
        out.append("    ops:\n" if write["ops"] else "    ops: []\n")
        out += [f"      - {flow(op)}\n" for op in write["ops"]]
    return "".join(out)


def flow(value: Any) -> str:
    text = yaml.safe_dump(
        value, default_flow_style=True, width=1_000_000, allow_unicode=True, sort_keys=False
    )
    return text.removesuffix("\n").removesuffix("\n...").strip()
