"""Build RuleGo chain JSON for pclib steps (docs/RULEGO_NOTES.md).

    from pclib import chains as c

    iteration = c.chain("reflexion_iter",
        nodes=[c.step("actor", "registry/policy_codegen.py"),
               c.step("eval", "registry/eval_run_tests.py", timeout=120),
               c.switch("route", [("msg.passed == true", "Pass")])],
        edges=[("actor", "eval"), ("eval", "route"), ("route", "done", "Pass")])
    main = c.chain("reflexion", root=True,
        nodes=[c.loop("trials", "chain:reflexion_iter", "msg.stop != true")])

Script paths are relative to the repo root and resolved under REPO (where RuleGo sees the
repo, /repo in the container). A node id is the step's name, so it becomes the slot id in
step keys and traces. write() emits each step node's stub file (see pclib.node) under
<dir>/<chain id>.nodes/ and points the node at it.
"""
import json
import os
from pathlib import Path

REPO = os.environ.get("PC_RULEGO_REPO", "/repo")


def step(node_id: str, script: str, timeout: float = 300, name: str | None = None,
         max_running: int = 2) -> dict:
    """A pclib step on RuleGo's x/python node. `timeout` bounds the step, in seconds;
    `max_running` caps concurrent runs of this node (about a third stay warm when idle)."""
    # The node's own timeout is a backstop a little beyond pclib's, so pclib reports the cause.
    return {"id": node_id, "type": "x/python", "name": name or node_id,
            "configuration": {"script": None, "timeout": f"{int(timeout) + 5}s",
                              "maxRunning": max_running},
            "_pclib": {"script": script, "timeout": timeout}}


def loop(node_id: str, do: str, condition: str, mode: int = 2) -> dict:
    """Repeat a node or `chain:<id>` while `condition` holds; each output feeds the next run.
    mode 2 returns the last iteration's message. Metadata `_break=true` stops early."""
    return {"id": node_id, "type": "while", "name": node_id,
            "configuration": {"condition": condition, "do": do, "mode": mode}}


def switch(node_id: str, cases: list[tuple[str, str]]) -> dict:
    """Route on expressions over msg/metadata; unmatched messages take `Default`."""
    return {"id": node_id, "type": "switch", "name": node_id,
            "configuration": {"cases": [{"case": c, "then": t} for c, t in cases]}}


def subchain(node_id: str, chain_id: str) -> dict:
    """Run another chain (or this one, recursively) and continue with its output."""
    return {"id": node_id, "type": "flow", "name": node_id,
            "configuration": {"targetId": chain_id, "extend": True}}


def chain(chain_id: str, nodes: list[dict], edges=(), root: bool = False, vars: dict | None = None) -> dict:
    """edges: (from, to) for Success, or (from, to, relation)."""
    ids = {n["id"] for n in nodes}
    conns = []
    for e in edges:
        frm, to, rel = (*e, "Success") if len(e) == 2 else e
        missing = {frm, to} - ids
        if missing:
            raise ValueError(f"chain {chain_id}: edge {frm}->{to} names unknown node(s) {sorted(missing)}")
        conns.append({"fromId": frm, "toId": to, "type": rel})
    rc = {"id": chain_id, "name": chain_id, "root": root}
    if vars:
        rc["configuration"] = {"vars": vars}
    return {"ruleChain": rc, "metadata": {"nodes": nodes, "connections": conns}}


def write(chain_json: dict, directory, repo_root=None) -> str:
    """Write <directory>/<chain id>.json plus a stub per step node in <chain id>.nodes/.
    `directory` must be inside the repo (default root: two levels above pclib/)."""
    directory = Path(directory).resolve()
    repo_root = Path(repo_root or Path(__file__).resolve().parent.parent)
    cid = chain_json["ruleChain"]["id"]
    out = json.loads(json.dumps(chain_json))
    stubs = directory / f"{cid}.nodes"
    for node in out["metadata"]["nodes"]:
        spec = node.pop("_pclib", None)
        if spec is None:
            continue
        stubs.mkdir(parents=True, exist_ok=True)
        stub = stubs / f"{node['id']}.py"
        target = f"{REPO}/{spec['script']}"
        stub.write_text(
            f'"""Generated by pclib.chains for node {node["id"]!r} of chain {cid!r}; do not edit."""\n'
            "from pclib.node import bind\n\n"
            f"Process = bind({target!r}, {node['id']!r}, timeout={spec['timeout']!r})\n")
        node["configuration"]["script"] = f"{REPO}/{stub.relative_to(repo_root)}"
    path = directory / f"{cid}.json"
    path.write_text(json.dumps(out, indent=2) + "\n")
    return str(path)
