"""pclib as a RuleGo x/python node, and the chain builder."""
import json
import sys
from pathlib import Path

import pytest

from pclib import chains as c
from pclib import node

ROOT = Path(__file__).resolve().parents[2]
STEP = Path(__file__).parent / "steps" / "counting_step.py"


def test_node_call_runs_once_and_maps_metadata(conn, run_id, tmp_path):
    meta = {"run_id": run_id, "task_id": "T9", "episode": "2", "_loopIndex": "1", "id": "chain", "note": "x"}
    msg = {"counter": str(tmp_path / "count.txt"), "n": 4}
    out = node.call(str(STEP), "actor", msg, meta)
    again = node.call(str(STEP), "actor", msg, meta)
    assert out == again and (tmp_path / "count.txt").read_text() == "ran\n"
    assert out["msg"]["n"] == 5
    assert out["metadata"]["run_id"] == run_id and out["metadata"]["episode"] == "2"
    assert json.loads(out["metadata"]["echo"]) == {"note": "x"}          # step meta in, meta out
    key, = conn.execute("select step_key from run.step where run_id = %s", (run_id,)).fetchone()
    assert key == "task=T9/ep=2/i=1/actor"


def test_bind_matches_the_x_python_signature(conn, run_id, tmp_path):
    process = node.bind(str(STEP), "reflector")
    out = process({"counter": str(tmp_path / "c.txt")}, {"run_id": run_id}, "STEP", "JSON")
    assert out["msg"]["executions"] == 1


def test_node_requires_run_id():
    with pytest.raises(ValueError, match="run_id"):
        node.call(str(STEP), "x", {}, {})


def test_chain_builder_writes_stubs(tmp_path):
    ch = c.chain("demo", root=True,
                 nodes=[c.step("a", "tests/contract/steps/counting_step.py", timeout=10),
                        c.switch("route", [("msg.n > 1", "Big")]), c.subchain("sub", "other")],
                 edges=[("a", "route"), ("route", "sub", "Big")])
    path = c.write(ch, tmp_path, repo_root=tmp_path)
    written = json.loads(Path(path).read_text())
    a = written["metadata"]["nodes"][0]
    assert a["configuration"]["script"] == "/repo/demo.nodes/a.py" and "_pclib" not in a
    stub = (tmp_path / "demo.nodes" / "a.py").read_text()
    assert "bind('/repo/tests/contract/steps/counting_step.py', 'a', timeout=10)" in stub
    assert written["metadata"]["connections"][1] == {"fromId": "route", "toId": "sub", "type": "Big"}
    with pytest.raises(ValueError, match="unknown node"):
        c.chain("bad", nodes=[c.step("a", "x.py")], edges=[("a", "b")])


def test_committed_spike_chains_are_current(tmp_path, monkeypatch):
    """rulego/spike/pclib/chains is generated by build.py; regenerate and compare."""
    sys.path.insert(0, str(ROOT / "rulego" / "spike" / "pclib"))
    import build
    for ch in build.CHAINS:
        c.write(ch, tmp_path, repo_root=tmp_path)
        cid = ch["ruleChain"]["id"]
        fresh = json.loads((tmp_path / f"{cid}.json").read_text())
        committed = json.loads((ROOT / "rulego/spike/pclib/chains" / f"{cid}.json").read_text())
        for n in fresh["metadata"]["nodes"]:          # stub paths differ only by location
            if n["type"] == "x/python":
                n["configuration"]["script"] = n["configuration"]["script"].replace(
                    "/repo/", "/repo/rulego/spike/pclib/chains/", 1)
        assert fresh == committed, f"{cid}: run rulego/spike/pclib/build.py"
